// Google Apps Script for surveyframe response collection
// Generated by surveyframe (export_google_sheet() or the SurveyBuilder)
// Target Google Sheet: {{SHEET_URL_COMMENT}}
//
// Setup:
// 1. Open the target Google Sheet
// 2. Go to Extensions > Apps Script
// 3. Paste this entire file, replacing any existing code
// 4. Add the Sheets advanced service: in the editor, Services > add
//    "Google Sheets API", with the identifier "Sheets". This is what lets the
//    collector store an answer literally; see appendResponseRow_() below for why
//    it matters and what happens without it.
// 5. Click Deploy > New deployment > Web app
// 6. Set "Who has access" to "Anyone"
// 7. Copy the Web App URL and paste it into the SurveyBuilder
//    under Survey > Google Sheets Setup

const SHEET_NAME = "Responses";
const UNMAPPED_SHEET_NAME = "Unmapped submissions";
const TARGET_SHEET_URL = {{TARGET_SHEET_URL}};
const EXPECTED_COLUMNS = {{EXPECTED_COLUMNS}};
const MAX_BODY_CHARS = 200000;

function doPost(e) {
  // Header work and the append run inside a script lock, so 2 submissions
  // cannot interleave while the header is created or extended.
  const lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    if (!e || !e.postData || !e.postData.contents) {
      throw new Error("Missing POST body.");
    }
    if (e.postData.contents.length > MAX_BODY_CHARS) {
      throw new Error("POST body too large.");
    }
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    let sheet = ss.getSheetByName(SHEET_NAME);
    if (!sheet) {
      sheet = ss.insertSheet(SHEET_NAME);
    }

    const data = JSON.parse(e.postData.contents);
    if (!data || Array.isArray(data) || typeof data !== "object") {
      throw new Error("POST body must be a JSON object.");
    }

    // Rows are mapped to the sheet's own header by name, never positionally
    // against EXPECTED_COLUMNS. Writing the header once at creation and then
    // building rows positionally silently corrupted every sheet whose
    // instrument gained an item mid-collection: the header stayed as first
    // deployed while rows arrived in the new order, so every column from the
    // insertion point onward was off by one. Nothing errored, the sheet stayed
    // well-formed, and read_responses() read it happily.
    const header = readHeader_(sheet);
    // A duplicate or blank heading makes the mapping ambiguous: an answer
    // could land in the wrong column, or in 2. The raw submission is kept on
    // a separate sheet with the reason, so nothing is mis-filed or lost.
    const problem = headerProblem_(header);
    if (problem) {
      let unmapped = ss.getSheetByName(UNMAPPED_SHEET_NAME);
      if (!unmapped) unmapped = ss.insertSheet(UNMAPPED_SHEET_NAME);
      appendDiagnosticRow_(unmapped, [new Date().toISOString(), problem, e.postData.contents]);
      return ContentService
        .createTextOutput(JSON.stringify({ status: "unmapped", message: problem }))
        .setMimeType(ContentService.MimeType.JSON);
    }
    const row = header.map(col => data[col] !== undefined ? String(data[col]) : "");
    // Throws when the answer cannot be stored literally, which the catch below
    // turns into status "error". There is one write path and it is the literal
    // one, so a status of "ok" means the row is on the sheet as submitted.
    appendResponseRow_(sheet, row);

    return ContentService
      .createTextOutput(JSON.stringify({ status: "ok", rows: sheet.getLastRow() - 1,
                                         stored: "raw" }))
      .setMimeType(ContentService.MimeType.JSON);

  } catch (err) {
    return ContentService
      .createTextOutput(JSON.stringify({ status: "error", message: err.toString() }))
      .setMimeType(ContentService.MimeType.JSON);
  } finally {
    lock.releaseLock();
  }
}

// A heading that is blank before the last filled column, or that appears more
// than once, leaves no single column for an answer.
function headerProblem_(header) {
  const seen = {};
  for (let i = 0; i < header.length; i++) {
    const name = header[i];
    if (name === "") return "The Responses sheet has a blank heading in column " + (i + 1) + ".";
    if (seen[name]) return "The Responses sheet has more than one column headed " + name + ".";
    seen[name] = true;
  }
  return "";
}

// Writes one response row literally, never as user-entered values.
//
// appendRow() and setValues() both parse a cell the way typing into it would,
// so an answer beginning with "=" became a formula: "=1+1" was stored as 2,
// and "=IMPORTXML(...)" was evaluated inside the researcher's own sheet.
// Numeric codes lost their leading zeros the same way.
//
// The documented way to store a value without parsing is the Sheets API's
// valueInputOption RAW, which the Sheets advanced service exposes here:
// https://developers.google.com/workspace/sheets/api/reference/rest/v4/ValueInputOption
// Google documents setValues() as applying user-entered semantics, so relying
// on the plain-text number format alone to suppress parsing rests on
// behaviour Google does not promise. RAW is the promise.
//
// Where the advanced service is unavailable, a response row is REFUSED rather
// than written through setValues(). The earlier version wrote it anyway and
// named the degradation in a `warning` field, which nothing could read: the
// respondent's page posts no-cors, so the browser sees only that the request
// left. The participant was shown "your response has been recorded" over an
// answer the collector had just altered. Failing closed leaves the page holding
// the only copy, which it can then offer as a download. Enable the service.
function appendResponseRow_(sheet, row) {
  if (!row.length) return;
  if (!sheetsApiAvailable_()) {
    throw new Error(
      "The Google Sheets advanced service is not enabled, so an answer " +
      "cannot be stored literally and this response was NOT saved. In the " +
      "Apps Script editor, add Services > Google Sheets API with the " +
      "identifier Sheets, then ask the participant to send again.");
  }
  const startRow = sheet.getLastRow() + 1;
  sheet.getRange(startRow, 1, 1, row.length).setNumberFormat("@");
  Sheets.Spreadsheets.Values.update(
    { values: [row.map(function (v) { return v === null ? "" : String(v); })] },
    sheet.getParent().getId(),
    sheet.getName() + "!A" + startRow,
    { valueInputOption: "RAW" }
  );
}

function sheetsApiAvailable_() {
  return typeof Sheets !== "undefined" && Sheets.Spreadsheets &&
    Sheets.Spreadsheets.Values;
}

// A diagnostic row, for the header and unmapped sheets. These hold a copy of a
// submission the collector could not file, so a best-effort write beats none:
// losing the copy is the worse failure. The plain-text format is applied and
// the row may still be coerced, which is acceptable for a record nothing reads
// programmatically. A response row never comes through here.
function appendDiagnosticRow_(sheet, row) {
  if (!row.length) return;
  const startRow = sheet.getLastRow() + 1;
  const target = sheet.getRange(startRow, 1, 1, row.length);
  target.setNumberFormat("@");
  if (sheetsApiAvailable_()) {
    Sheets.Spreadsheets.Values.update(
      { values: [row.map(function (v) { return v === null ? "" : String(v); })] },
      sheet.getParent().getId(),
      sheet.getName() + "!A" + startRow,
      { valueInputOption: "RAW" }
    );
    return;
  }
  target.setValues([row]);
}

// Returns the sheet's live header, creating or extending it as needed.
// An existing column never moves, so rows already collected stay valid. A
// column the instrument has gained since the last deployment is appended at
// the right-hand end, which is why a redeploy after an instrument change is
// safe.
function readHeader_(sheet) {
  let header = [];
  if (sheet.getLastRow() > 0 && sheet.getLastColumn() > 0) {
    // Headings are read exactly as written. Trimming could merge a heading
    // with a stray space into a declared column name.
    header = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0]
                  .map(h => String(h));
    while (header.length && header[header.length - 1] === "") {
      header.pop();
    }
  }

  if (header.length === 0) {
    header = EXPECTED_COLUMNS.slice();
    sheet.getRange(1, 1, 1, header.length).setValues([header]);
    styleHeader_(sheet, 1, header.length);
    return header;
  }

  const missing = EXPECTED_COLUMNS.filter(col => header.indexOf(col) === -1);
  if (missing.length) {
    sheet.getRange(1, header.length + 1, 1, missing.length).setValues([missing]);
    styleHeader_(sheet, header.length + 1, missing.length);
    header = header.concat(missing);
  }
  return header;
}

function styleHeader_(sheet, startColumn, numColumns) {
  sheet.getRange(1, startColumn, 1, numColumns)
       .setFontWeight("bold")
       .setBackground("#1a1a2e")
       .setFontColor("#ffffff");
}

function doGet(e) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(SHEET_NAME);
  if (!sheet) {
    return ContentService
      .createTextOutput(JSON.stringify({ status: "ok", rows: 0 }))
      .setMimeType(ContentService.MimeType.JSON);
  }
  const lastRow = sheet.getLastRow();
  return ContentService
    .createTextOutput(JSON.stringify({ status: "ok", rows: Math.max(0, lastRow - 1) }))
    .setMimeType(ContentService.MimeType.JSON);
}
